{{- if not .Values.azure.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  clientID: {{ .Values.azure.clientID | b64enc | quote }}
  clientSecret: {{ .Values.azure.clientSecret | b64enc | quote }}
  tenantID: {{ .Values.azure.tenantID | b64enc | quote }}
  subscriptionID: {{ .Values.azure.subscriptionID | b64enc | quote }}
  certificatePath: {{ .Values.azure.certificatePath | b64enc | quote }}
  certificatePassword: {{ .Values.azure.certificatePassword | b64enc | quote }}
  userAssertionString: {{ .Values.azure.userAssertionString | b64enc | quote }}
{{- end }}
